JMAP news posted by Tuan LE CONG
jmapio/jmapio.github.io pull request #8
Opened 2019-07-07 08:07 UTC by yvesdaxmaz

Jmap Barcamp 2019

2019-07-07 22:46 UTC, marclaporte commented on .gitmodules
> +	url = https://github.com/yvesdaxmaz/jmap.git
Really?

2019-07-08 01:47 UTC, neilj requested changes

2019-07-08 01:47 UTC, neilj commented on news.md
> +## Tuan LE CONG
The title should be the title of the article: "Jmap Barcamp 2019"

2019-07-08 01:47 UTC, neilj commented on .gitmodules
> +	url = https://github.com/yvesdaxmaz/jmap.git
Yes, this needs to be removed.

2019-07-12 00:41 UTC, yvesdaxmaz commented on .gitmodules
> +	url = https://github.com/yvesdaxmaz/jmap.git
I have update the .gitmodules

2019-07-12 10:02 UTC, merged